version: '3.8'

services:
  devcontainer:
    # image: mcr.microsoft.com/devcontainers/base:ubuntu
    build:
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: newsletter
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost

  db:
    image: docker.io/postgres:latest
    network_mode: service:devcontainer
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: newsletter

  redis:
    image: docker.io/redis:latest
    network_mode: service:devcontainer
    restart: unless-stopped

volumes:
  postgres-data:
