version: '3.8'

services:
    devcontainer:
        # image: mcr.microsoft.com/devcontainers/base:ubuntu
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: newsletter
            POSTGRES_PORT: 5432
            POSTGRES_HOST: db

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: newsletter

    redis:
        image: redis:latest
        restart: unless-stopped

volumes:
    postgres-data:
