application:
  host: 127.0.0.1
  base_url: http://127.0.0.1
database:
  require_ssl: false
email_client:
  api_url: https://sandbox.api.mailtrap.io/api/send/{inbox_id}
  sender_email: test@email.com
  secret: secret