name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          # must be the same as in .env file
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: newsletter
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: rui314/setup-mold@v1
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: rui314/setup-mold@v1
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  linting:
    name: Clippy linting
    runs-on: ubuntu-latest
    steps:
      - uses: rui314/setup-mold@v1
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run linter
        run: cargo clippy -- -D warnings

# Commented out to reduce pipeline run time
#  coverage:
#    name: Code coverage
#    runs-on: ubuntu-latest
#    steps:
#      - uses: rui314/setup-mold@v1
#      - uses: actions/checkout@v3
#      - uses: dtolnay/rust-toolchain@stable
#      - name: Install tarpaulin
#        run: cargo install cargo-tarpaulin
#      - name: Generate code coverage
#        run: cargo tarpaulin --verbose --workspace
